apiVersion: v1
kind: Service
metadata:
  name: dark-weather-service
spec:
  type: NodePort
  selector:
    app: dark-weather
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dark-weather-deployment
  labels:
    app: dark-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dark-weather
  template:
    metadata:
      labels:
        app: dark-weather
    spec:
      containers:
      - name: dark-weather
        image: dark-weather-image
        ports:
        - containerPort: 5001