apiVersion: v1
kind: Namespace
metadata:
  name: darkweather
  
---

apiVersion: v1
kind: Service
metadata:
  name: dark-weather-service
  namespace: darkweather
spec:
  type: NodePort
  selector:
    app: dark-weather
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 30001

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dark-weather-deployment
  namespace: darkweather
  labels:
    app: dark-weather
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dark-weather
  template:
    metadata:
      labels:
        app: dark-weather
    spec:
      containers:
      - name: dark-weather
        image: jduarte104/darkweather:11
        ports:
        - containerPort: 5001
